* Operadores Lógicos, são eles:
* AND e
* OR ou
* NOT negação

REPORT: Z_OP_LÓGICOS.

DATA: V_NOTA1 TYPE P,
      V_NOTA2 TYPE P,
      V_MEDIA TYPE P.

V_NOTA1 = 13.
V_NOTA2 = 9.
V_MEDIA = (V_NOTA1 + V_NOTA2) / 2.

IF V_MEDIA GE 7 AND V_MEDIA LT 10.
    WRITE: / 'ALUNO APROVADO COM MEDIA: ', V_MEDIA.
ELSEIF V_MEDIA GE 10.
    WRITE: / 'PARABÉNS, ALUNO APROVADO COM MÉDIA: ', V_MEDIA.
ELSEIF V_MEDIA LT 7.
    WRITE: / 'ALUNO REPROVADO COM MÉDIA: ', V_MEDIA.
ENDIF.